services:
  ruby:
    image: ruby:4.0.4
    working_dir: /var/source
    user: ${CURRENT_UID}:${CURRENT_GID}
    volumes:
      - .:/var/source
      - ruby-gems:/usr/local/bundle

  node:
    image: node:26
    working_dir: /var/source
    user: ${CURRENT_UID}:${CURRENT_GID}
    volumes:
      - .:/var/source

volumes:
  ruby-gems:
